name: Test rspec-graphql_response
on:
  pull_request:
  push:
  paths-ignore:
    - README.md
    - CODE_OF_CONDUCT.md
    - LICENSE.txt
    - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler_cache: true
      - run: bin/rspec